 /**
 * Αλίκη Δαγλή 44841
 * Ανδρέας Μπελόκας 40443
 * Γιώργος ΣΥΡΑΝΙΔΗΣ 39280
 **/
package concertticketsteller;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TellerFrame extends javax.swing.JFrame {

    static final Map<String, String> TYPES = new HashMap<>();
    private static ConcertTicketsTeller teller;

    static {
        TYPES.put("Adult","0");
        TYPES.put("Student", "30");
        TYPES.put("Children", "50");
        TYPES.put("Unemployed", "50");
    }

    /**
     * Creates new form TellerFrame
     */
    public TellerFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        concertComboBox = new javax.swing.JComboBox<>();
        dateComboBox = new javax.swing.JComboBox<>();
        tierComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seatComboBox = new javax.swing.JComboBox<>();
        nameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(onClose());
        setTitle("Teller");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                close(evt);
            }
        });

        jLabel1.setText("Concert :");

        jLabel2.setText("Tier :");

        concertComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getConcerts()));
        concertComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concertComboBoxActionPerformed(evt);
            }
        });

        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getDates(concertComboBox.getItemAt(0))));
        dateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboBoxActionPerformed(evt);
            }
        });

        tierComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getTiers(concertComboBox.getItemAt(0))));
        tierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tierComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Type :");

        String[] a = new String[TYPES.keySet().size()];
        a=TYPES.keySet().toArray(a);
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(a));

        jLabel4.setText("Seat No :");

        jLabel5.setText("Name :");

        seatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getSeats(concertComboBox.getItemAt(0),tierComboBox.getItemAt(0), (String) dateComboBox.getItemAt(0))));

        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        jScrollPane1.setViewportView(infoTextArea);

        jLabel6.setText("Info :");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");

        jLabel7.setText("Date : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTextField)
                            .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tierComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(concertComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(concertComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(printButton)
                    .addComponent(refreshButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void close(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close
        try {
            teller.exit();
        } catch (IOException ex) {
            Logger.getLogger(TellerFrame.class
                    .getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_close

    private void concertComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concertComboBoxActionPerformed
        seatComboBox.setEnabled(true);
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getDates((String) concertComboBox.getSelectedItem())));
        tierComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getTiers((String) concertComboBox.getSelectedItem())));
        seatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getSeats((String) concertComboBox.getSelectedItem(), (String) tierComboBox.getSelectedItem(), (String) dateComboBox.getSelectedItem())));
        if(seatComboBox.getItemAt(0).equals("FULL")){
            seatComboBox.setEnabled(false);
            infoTextArea.setText("");
            infoTextArea.setText("Full please choose another");
        }
    }//GEN-LAST:event_concertComboBoxActionPerformed

    private void tierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tierComboBoxActionPerformed
        seatComboBox.setEnabled(true);
        seatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getSeats((String) concertComboBox.getSelectedItem(), (String) tierComboBox.getSelectedItem(), (String) dateComboBox.getSelectedItem())));
        if(seatComboBox.getItemAt(0).equals("FULL")){
            seatComboBox.setEnabled(false);
            infoTextArea.setText("");
            infoTextArea.setText("Full please choose another");
        }
    }//GEN-LAST:event_tierComboBoxActionPerformed

    private void dateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboBoxActionPerformed
        seatComboBox.setEnabled(true);
        tierComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getTiers((String) concertComboBox.getSelectedItem())));
        seatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(teller.getSeats((String) concertComboBox.getSelectedItem(), (String) tierComboBox.getSelectedItem(), (String) dateComboBox.getSelectedItem())));
        if(seatComboBox.getItemAt(0).equals("FULL")){
            seatComboBox.setEnabled(false);
            infoTextArea.setText("");
            infoTextArea.setText("Full please choose another");
        }
    }//GEN-LAST:event_dateComboBoxActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        boolean addTicket = teller.addTicket((String) concertComboBox.getSelectedItem(),
                (String) tierComboBox.getSelectedItem(), 
                (String) dateComboBox.getSelectedItem(), 
                (((String) seatComboBox.getSelectedItem()).matches("-?\\d+(\\.\\d+)?")?(String) seatComboBox.getSelectedItem():"0"), 
                nameTextField.getText(), 
                TYPES.get((String) typeComboBox.getSelectedItem()));
        if(addTicket){
            String ticket = teller.getTicket(nameTextField.getText(), 
                    (String) concertComboBox.getSelectedItem(), 
                    (String) dateComboBox.getSelectedItem());
            System.out.println("Ticket : "+ticket);
            String[] t = ticket.split(":");
            infoTextArea.setText(
                     "Conncert Title : "+t[1]+"\n"
                    +"Concert Hall : "+t[2]+"\n"
                    +"Name : "+t[0]+"\n"
                    +"Tier : "+t[3]+"\n"
                    +"Seat : "+(t[4].equals("0")?"Not Numbered":t[4])+"\n"
                    +"Price : "+(t[6].equals("0")?t[5]:(Float.parseFloat(t[5])-(Float.parseFloat(t[5])*Float.parseFloat(t[6]))))+"  "
                    +"Discount : "+(Float.parseFloat(t[6])*100)+"%\n"
                    +"Date : "+t[7]+"  "
                    +"Time : "+t[8]+":"+t[9]);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TellerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        teller = new ConcertTicketsTeller();
        /* Create and display the form */
        if (teller.connect()) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new TellerFrame().setVisible(true);
                }
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> concertComboBox;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton printButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JComboBox<String> seatComboBox;
    private javax.swing.JComboBox<String> tierComboBox;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration//GEN-END:variables

    private int onClose() {
        return EXIT_ON_CLOSE;
    }
}
